build-lambda:
  stage: build
  image: docker:latest
  services:
    - docker:dind
  before_script:
    - apk add --no-cache make aws-cli
  script:
    - make docker-build IMAGE_TAG=$IMAGE_TAG
    - make docker-push IMAGE_TAG=$IMAGE_TAG
  rules:
    - if: $CI_COMMIT_BRANCH == "main"
    - if: $CI_COMMIT_BRANCH =~ /^feature\/.*$/
